create schema if not exists library;

create table if not exists library.person
(
    id         int generated by default as identity primary key,
    name       varchar(30) not null unique,
    birth_year int
);

create table if not exists library.book
(
    id               int generated by default as identity primary key,
    title            varchar(50) not null unique,
    author           varchar(30) not null,
    publication_year int,
    owner_id         int         null references library.person (id) on delete set null
);


